# Generated by Django 5.2.8 on 2025-12-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20251201_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='issues', to='webapp.type'),
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_types', to='webapp.issue')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_issues', to='webapp.type')),
            ],
        ),
    ]
